# Generated by Django 2.2.7 on 2020-03-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_auto_20200311_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
